apiVersion: v1
kind: Pod
metadata:
  namespace: qa
  name: webapp
  labels:
    app: webapp
spec:
  containers:
  - name: webapp
    image: mylandmarktech/java-web-app
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: qa
  name: appsvc
spec:
  type: ClusterIP
  selector:
    app: webapp
  ports:
    - port: 80
      targetPort: 8080