apiVersion: v1    
kind: Pod     
metadata:
  name: webapp 
  namespace: dev 
  labels:
    app: weapp  
spec:
  containers:
  - name: webapp   
    image: mylandmarktech/maven-web-app   
    ports:
    - containerPort: 8080  